### ISSUE TITLE
Add support for Knative Services

### ISSUE THREAD

**Issue by cardil** [HLTech/judge-d#114]
**Is your feature request related to a problem? Please describe.**
Current implementation of K8s service locator looks for pods, and fetches their image. Image is parsed so that name and version of a service is resolved.

[Knative project](https://knative.dev/) introduces serverless programming into K8s world. Knative services scale their pods to zero if there is no traffic going into them. In that way Judge-d will not find them as a service.

**Describe the solution you'd like**
To support Knative services, one should look on `service.serving.knative.dev` resource type, and took image from it's spec section. Below example Kservice can be seen:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: forwarder
  namespace: demo
spec:
  template:
    spec:
      containers:
        - name: forwarder
          image: quay.io/cardil/wathola-forwarder:v0.7.0
          readinessProbe:
            httpGet:
              path: /healthz
```

**Describe alternatives you've considered**
none

**Additional context**
